name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # 每天生成1次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: zezhongding     # <--- 改这里
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push generated snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate github-contribution-grid-snake.svg"
          add: "dist/*.svg"
